feat /added weather component and weather route started
Penguins-ims-india/Helpful-Hiker pull request #1
Opened 2024-05-21 23:43 UTC by jrob112

2024-05-22 20:03 UTC, AlexPHebert2000 commented on client/components/Weather.jsx
> +    axios.get('api/weather')
This should be '/weather'. there is no /api endpoint

2024-05-22 20:05 UTC, AlexPHebert2000 commented on client/components/Weather.jsx
> +    return (celsius * 9/5) + 32;
Use Math.floor(((celsius * 9/5) + 32) * 100) / 100 to round to the nearest hundredth of a degree

2024-05-22 20:06 UTC, AlexPHebert2000 commented on client/components/Weather.jsx
> +    <Box sx={styleOrangeBox}>
We dont have a 'styleOrangeBox' for this project

2024-05-22 20:09 UTC, AlexPHebert2000 commented on server/routes/weather.js
> +  const userIpAddress = req.clientIp;
request IP middleware is not installed on this project. We used it in the previous project to get the user's location. The weather should be based on the location of the hike so the ip address should not be necessary in this project

2024-05-22 20:10 UTC, AlexPHebert2000 requested changes
Please take a look at the comments I left and resolve them

2024-05-24 00:30 UTC, AlexPHebert2000 approved these changes

2024-05-24 00:33 UTC, uhrinuh approved these changes

2024-05-24 00:33 UTC, merged